[package]
name = "img_maniac"
version = "0.2.0"
edition = "2021"
authors = ["Allen Dang <allengnr@gmail.com>"]
description = "A powerful image viewer"

[package.metadata.bundle]
name = "img_maniac"
identifier = "com.allendang.img_maniac"
icon = ["icon/app.png"]
version = "0.2.0"
copyright = "Copyright (c) Allen Dang 2023. All rights reserved."
category = "Developer Tool"
short_description = "A powerful image viewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
bevy = { version = "0.10", default-features = false, features = [
  "bevy_asset",         # Assets management
  "bevy_scene",         # Scenes management
  "bevy_winit",         # Window management
  "bevy_render",        # Rendering framework core
  "bevy_core_pipeline", # Common rendering abstractions
  "bevy_pbr",           # 3D (physically-based) rendering
  "bevy_text",          # Text/font rendering
  "bevy_ui",            # UI toolkit     # Graphics Rendering
  "png",
  "bmp",
  "dds",
  "jpeg",
  "tga",
  "exr",
  "hdr",
  "ktx2",
  "basis-universal",
  "zstd",               # needed if using zstd in KTX2 files
] }
# bevy-inspector-egui = "0.18.3"
bevy_mod_picking = "0.12.0"
